### ISSUE TITLE
Request for Complete Code

### ISSUE THREAD

**Issue by Anonymo22** [THUDM/GraphAlign#1]
Thank you for your great work!

 I am very interested in this project, but I have encountered several issues with the incomplete code in the repository that prevent me from reproducing the results presented in your paper. 

Specifically, the repository appears to be missing the following files: **'fmoe.py'**

Could you please update the repository with these files at your earliest convenience? I appreciate your assistance and look forward to progressing with my implementation.

**Comment by THINK2TRY** [comment]
@Anonymo22 Apologize for the late response and thank you for your attention to our work! GraphAlign relies on FastMoE to implement the mixture-of-feature expert design. So to run our code, you can first run `bash setup.sh` to install the dependencies (as mentioned in README). Hope it helps !

**Comment by zhan72** [comment]
If you want a more specific implementation of MoE in GraphAlign, you can find it [here](https://github.com/zhan72/fastmoe.git).

**Comment by Anonymo22** [comment]
Thank you! Will try it today.

**Comment by Anonymo22** [comment]
Thank you!
